Retreat
Haochenlucas/GamingSupervisor pull request #59
Opened 2018-04-10 06:48 UTC by yatzyt

Known issues: super choppy

I'm pretty bad at working with concurrency and optimization that's not algorithms, so I don't know if introducing bg workers or similar methods would help here.

I'm probably gonna rework my training data set to have less data, so this will hopefully not be as bad.

2018-04-11 20:17 UTC, Haochenlucas approved these changes

2018-04-12 04:18 UTC, theoculus8 requested changes
I would want to see how this performs on Haochen's laptop before we merge.

2018-04-12 04:18 UTC, theoculus8 commented on GamingSupervisor/replayParse/Retreat.cs
> +            using (StreamWriter file = new StreamWriter(Path.Combine(Environment.CurrentDirectory, "input.txt")))
This should either be sent as a command line argument or sent to standard in of the process.

2018-04-12 04:18 UTC, theoculus8 commented on GamingSupervisor/replayParse/Retreat.cs
> +            Process p = new Process();
This should probably be a long running process

2018-04-12 04:18 UTC, theoculus8 commented on GamingSupervisor/replayParse/Retreat.cs
> +            p.StartInfo.FileName = "retreat_predict.exe";
The code for this exe should be added to github

2018-04-12 04:18 UTC, theoculus8 commented on GamingSupervisor/GamingSupervisor/ReplayAnalyzer.cs
> +            bool shouldRetreat = Retreat.CreateInputFile(myID: fHID,
We could maybe do something similar to what I did in LiveAnalyzer where I send a press button command to dota only if one second has passed since the last send. If there still is a delay issue we could try having a queue of threads where we spin off a thread once a second to send data to the process and return the result. Every loop we could check the front of the queue to see if we can tryjoin the thread and get the result.

2018-04-18 21:19 UTC, merged